FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
COPY . .
RUN chmod +x cuentas-movimientos-service/mvnw
RUN cuentas-movimientos-service/mvnw -f cuentas-movimientos-service/pom.xml clean package -DskipTests
EXPOSE 8082
CMD ["java", "-jar", "cuentas-movimientos-service/target/cuentas-movimientos-service-0.0.1-SNAPSHOT.jar"]